### ISSUE TITLE
Is there any getting started document?

### ISSUE THREAD

**Issue by gshiva** [tomzo/gocd#1]
I would like to give this a try to compare it with Jenkins DSL driven pipelines. I looked at

https://github.com/gocd/gocd/issues/1133

and it seems that that is what I would like to achieve.

It is not clear though on how to get started

i.e. has this stuff been merged to the gocd main repo 
or should I fork this and build

Also whether there are plans to make this feature mainline would help in adoption

**Comment by tomzo** [comment]
Hi @gshiva 

The work is still in progress and at least 2 more PRs have to be merged in mainline. It will definitely be there, although I don't know when. There is some significant effort needed from core Go team to review last PRs.

I have written documentation on how to add `configrepo` plugin - the PR is [here](https://github.com/gocd/documentation/pull/212) . It should clarify some things. Feedback is welcome.

If you want to try this feature already, you'll have to build server from my fork. I am continuously building and deploying a server from branch 15.3 - (it is not Go 15.3 really, just old name). In that server I have about 20 git repositories in which I have defined pipelines using [JSON configuration plugin](https://github.com/tomzo/gocd-json-config-plugin). [This](https://github.com/tomzo/docker-gocd-ide) can help you to build server quickly in docker.

But please note that extension point API might change a little, because it was not released yet. And there still might be some bugs that make Go a little unstable.

I was using jenkins DSL a little bit before moving to gocd. I initiated the idea and developed most of https://github.com/gocd/gocd/issues/1133 so I think I know what are talking about.

Do you have any more specifics on what kind of DSL you'll like to develop? I can help to get you started.

Lastly I encourage you to [join gitter channel](https://gitter.im/gocd/gocd) were gocd team and community talks.

**Comment by gshiva** [comment]
Will reopen when I look into checking out the pipeline feature
